### ISSUE TITLE
How can I join the Slack channel?

### ISSUE THREAD

**Issue by wasadigi** [paypal/InnerSourceCommons#202]
Hello,

I have found the link to the heroku app that is supposed to send an invite, but it is down. Is there any other way to join the channel?

Many thanks,

Olivier

**Comment by lenucksi** [comment]
The inviter is currently suspended, please write an email to questions@innersourcecommons.org to get an invitation.

**Comment by NewMexicoKid** [comment]
@lenucksi 's PR added the instructions for e-mailing questions@innersourcecommons.org in case of the inviter being down, so we can probably close this issue.
