### ISSUE TITLE
Check recipients of questions@innersourcecommons.org

### ISSUE THREAD

**Issue by dsugrobov** [paypal/InnerSourceCommons#209]
Want to join to ISC channel in Slack. During the period of outage of application for invitations I have to write email to questions@innersourcecommons.org

After mail was sent, I received several notices about wrong recipients:

> The following message to <[deleted]@paypal.com> was undeliverable.
> The reason for the problem:
> 5.1.0 - Unknown address error 550-'5.4.1 [[deleted]@paypal.com]: Recipient address rejected: Access denied

**Comment by cewilliams** [comment]
Yes, that email alias has some older email addresses attached to it. As the Commons stands up as a separate organization that will be fixed. :)
