### ISSUE TITLE
Logo in SVG 

### ISSUE THREAD

**Issue by dsugrobov** [paypal/InnerSourceCommons#210]
Going to create a presentation on the Innersource topic. The problem is to find ISC logo in big resolution in a good quality.

The idea is to post somewhere logo in vector.

**Comment by cewilliams** [comment]
There's a copy of it here in the repo: https://github.com/paypal/InnerSourceCommons/blob/master/assets/logos/ISLogo-1-0.svg

You can also get it through the website here: http://innersourcecommons.org/assets/logos/ISLogo-1-0.svg
