### ISSUE TITLE
Link to InnerSource OSCON slides is not working on the contribute page

### ISSUE THREAD

**Issue by HaRo87** [paypal/InnerSourceCommons#64]
Hi @cewilliams,
I've found out that the [link](https://paypal.github.io/assets/files/AntiSilo-OSCON-US-2015.pdf) to your OSCON 2015 slides on the [contribute](https://paypal.github.io/InnerSourceCommons/contribute/) site is not working. 

I would be happy to fix that but I do not have any experience with GitHub pages yet. Anything special about it, or is it "just" fixing the link in the appropriate .md file?

<img width="555" alt="page_not_found" src="https://cloud.githubusercontent.com/assets/5933065/18880266/99c82dd6-84d7-11e6-9cc2-8ab0ef1f716c.png">

**Comment by cewilliams** [comment]
Yup, this is broken! Thanks for finding that. Yes, please send in a PR for this change. Thanks!

**Comment by HaRo87** [comment]
Hi @cewilliams,
is there any way of assigning that issue to me?

**Comment by cewilliams** [comment]
Looks like there is!

**Comment by marcucci** [comment]
This works for me. Looks like the issue can be closed.

**Comment by HaRo87** [comment]
Done. ;)
